export const INTENTS = {
  luxury: {
    keywords: [
      "rico",
      "millonario",
      "lujo",
      "luxury",
      "premium",
      "elegante",
      "caro",
      "exitoso",
      "vip",
      "famoso",
      "empresario",
      "dinero",
      "yate",
      "jet privado",
      "gucci",
      "rolex",
    ],
    preset: "luxury",
  },

  cinematic: {
    keywords: [
      "pelicula",
      "cine",
      "cinematic",
      "netflix",
      "hollywood",
      "movie",
      "actor",
      "drama",
      "epico",
      "trailer",
      "poster",
      "film",
      "director",
    ],
    preset: "netflix",
  },

  cyberpunk: {
    keywords: [
      "cyberpunk",
      "futurista",
      "neon",
      "blade runner",
      "robot",
      "futuristic",
      "sci fi",
      "tecnologia",
      "future",
      "future city",
    ],
    preset: "cyberpunk",
  },

  anime: {
    keywords: [
      "anime",
      "manga",
      "otaku",
      "japones",
      "naruto",
      "dragon ball",
      "one piece",
      "anime style",
      "studio ghibli",
    ],
    preset: "anime",
  },

  fitness: {
    keywords: [
      "fitness",
      "gym",
      "musculoso",
      "ejercicio",
      "fit",
      "six pack",
      "bodybuilder",
      "deportivo",
      "atlético",
      "muscle",
    ],
    preset: "fitness",
  },

  office: {
    keywords: [
      "ceo",
      "linkedin",
      "corporativo",
      "oficina",
      "trabajo",
      "business",
      "executive",
      "profesional",
      "empresarial",
    ],
    preset: "office",
  },

  beach: {
    keywords: [
      "playa",
      "beach",
      "vacaciones",
      "mar",
      "isla",
      "palmeras",
      "arena",
      "tropical",
      "hawaii",
    ],
    preset: "beach",
  },

  sunset: {
    keywords: [
      "atardecer",
      "sunset",
      "golden hour",
      "sol",
      "orange sky",
      "cielo naranja",
    ],
    preset: "sunset",
  },

  // NUEVO: intención ropa / outfit
  clothing: {
    keywords: [
      "ropa",
      "outfit",
      "traje",
      "vestido",
      "camisa",
      "playera",
      "shirt",
      "dress",
      "fashion",
      "moda",
      "jacket",
      "chaqueta",
      "hoodie",
      "uniforme",
      "suit",
      "poner traje",
      "cambiar ropa",
      "vestirme",
      "ropa elegante",
      "ropa formal",
    ],
    preset: "luxury",
  },
};
